<a href="https://colab.research.google.com/github/Seferp/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```



### Funkcje statystyczne

In [4]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [5]:
price.sum()

4650.1

In [6]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [7]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [8]:
np.sum(price)

4650.1

min()

In [9]:
np.min(price)

11.7

max()

In [10]:
np.max(price)

2000.0

median()

In [11]:
np.median(price)

12.6

mean()

In [15]:
np.mean(price, axis = 0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std()

In [13]:
np.std(price)

622.3781502877133

var()

In [14]:
np.var(price)

387354.5619555555